"""
Every abbreviation, code and symbol the dashboard shows, in one place.

This is the single source for the in-app Legend (served by /api/glossary) and
for the README's Glossary section (generated by `markdown()`; a test fails if
the README drifts from it). Add a term here when the dashboard gains one.

Each group: (key, title, [(term, name, meaning), ...]).
"""
from typing import Dict, List

GROUPS = [
    ('smc', 'Smart Money Concepts (the protocol)', [
        ('SMC', 'Smart Money Concepts', 'Reading a chart for the footprints large institutions leave: where they bought or sold, and where other traders\' stops sit.'),
        ('HH / HL', 'Higher high / higher low', 'Each swing high and swing low above the last one: a bullish structure, the basis for a long.'),
        ('LH / LL', 'Lower high / lower low', 'Each swing high and swing low below the last one: a bearish structure, the basis for a short.'),
        ('Swing high / low', 'Swing point', 'A candle whose high (low) is beyond the candles either side of it: 3 each side on daily charts, 2 on 15m and 5m.'),
        ('BOS', 'Break of structure', 'The first close beyond a previous swing high (or low, for a short): the trend continuing.'),
        ('CHoCH', 'Change of character', 'After a sweep, a candle closing back beyond the last minor swing point: the turn that is the entry signal.'),
        ('OB', 'Order block', 'The body of the last opposite-colour candle before a strong move: where the move was launched. Drawn as a blue box.'),
        ('FVG', 'Fair value gap', 'A three-candle gap inside a strong move (candle 1 and candle 3 don\'t overlap), so price skipped that range. Drawn as amber boxes.'),
        ('BSL', 'Buy-side liquidity', 'Untaken swing highs above price, where buy stops cluster. A long\'s target.'),
        ('SSL', 'Sell-side liquidity', 'Untaken swing lows below price, where sell stops cluster. A short\'s target.'),
        ('Liquidity pool', 'Resting orders', 'A level where stops and orders gather (BSL, SSL, yesterday\'s high or low, the opening range). Price is often drawn to it.'),
        ('Leg', 'The impulse move', 'The move from its origin to its far end after the break of structure.'),
        ('Origin', 'Where the leg started', 'The leg\'s first extreme: a low for a long, a high for a short. The provisional stop sits just beyond it.'),
        ('Displacement', '"Massive" move', 'A leg at least 1.5 ATR (daily) or 2 × the 15m ATR (intraday) from origin to break.'),
        ('EQ', 'Equilibrium', 'The 50% midpoint of the leg. Drawn as the dashed "EQ 50%" line.'),
        ('Discount / premium', 'The cheap / expensive half', 'Below EQ is discount, where longs are taken; above EQ is premium, where shorts are taken.'),
        ('Leg position', 'How far price has come back', 'Distance back from the leg\'s origin: 0% at the origin, 50% at EQ. Must be under 50%.'),
        ('Zone', 'The alert zone', 'The order block, widened to any open FVG in the discount (or premium) half. Where the watcher waits for price.'),
        ('Sweep', 'Liquidity grab', 'Price briefly taking out a recent swing low (high, for a short), triggering the stops there, before turning.'),
        ('Tap', 'Into the zone', 'The first candle that trades into the zone after it was set.'),
    ]),
    ('trade', 'Trades and risk', [
        ('R:R', 'Reward-to-risk', '(target − entry) ÷ (entry − stop). 1:3 means the target is three times as far as the stop.'),
        ('1:3 / 1:2', 'Minimum R:R', 'Swing alerts need at least 1:3, intraday alerts at least 1:2 (both tunable).'),
        ('R', 'Result in risk units', 'A trade\'s result as a multiple of what it risked: +2.4R made 2.4× the risk, −1R hit the stop.'),
        ('*', 'Provisional', 'Before the trigger: the stop is beyond the whole leg\'s origin. The real stop, beyond the sweep, is tighter.'),
        ('Stop*', 'Provisional stop', 'The chart line for that provisional stop.'),
        ('Long (up triangle)', 'Buy setup', 'Bullish structure; profit if price rises.'),
        ('Short (down triangle)', 'Sell setup', 'Bearish structure; profit if price falls.'),
        ('F&O', 'Futures & options', 'NSE stocks with derivatives. A swing short (held overnight) needs them.'),
        ('MIS', 'Margin intraday square-off', 'An intraday product: positions, shorts included, must close the same day. Any stock can be shorted this way.'),
        ('Square-off', 'Closing out', 'Exiting an intraday position. NiftyWhale squares off open intraday trades at 15:20.'),
        ('Entry cutoff', 'No new entries', 'Intraday CHoCHs after 14:30 are rejected.'),
        ('Paper trade', 'An alert taken on paper', 'Every entry alert, followed as if taken exactly: in at the CHoCH close, out at the target or the stop (or the 15:20 square-off, intraday), no costs. Nothing is ever ordered.'),
    ]),
    ('ind', 'Chart indicators and levels', [
        ('O / H / L / C', 'Open, high, low, close', 'A candle\'s four prices. The magnet snaps to these; the tooltip underlines the one it snapped to.'),
        ('OHLC', 'Open-high-low-close', 'A candle\'s four prices together.'),
        ('Vol', 'Volume', 'Shares traded in the candle.'),
        ('ATR', 'Average true range', 'Average candle range over 14 candles (Wilder smoothing): how much a stock typically moves.'),
        ('ATR%', 'ATR as % of price', 'Daily ATR divided by price. The swing screen needs over 1.5%, intraday 1% or more.'),
        ('Δ est.', 'Estimated delta', 'Buying minus selling volume, estimated from where each 1-minute candle closed in its range. True delta needs tick data.'),
        ('Cum Δ', 'Cumulative delta', 'Running total of delta: since 09:15 on intraday charts, across the visible range on daily charts.'),
        ('VWAP', 'Volume-weighted average price', 'The average price weighted by volume, from 09:15 each session. Purple line.'),
        ('ORB', 'Opening range (breakout)', 'The high-low of the first 15 minutes, shaded across the session.'),
        ('ORB▲ / ORB▼', 'Opening range breakout / breakdown', 'The first candle closing above (below) the opening range.'),
        ('OR H / OR L', 'Opening range high / low', 'The first 15-minute candle\'s high and low, as lines when the ORB box is off.'),
        ('PDH / PDL', 'Previous day high / low', 'Yesterday\'s high and low: common intraday liquidity pools and targets.'),
        ('BB', 'Bollinger Bands', '20-candle average (dashed) ± 2 standard deviations, shaded.'),
        ('EQ 50%', 'Equilibrium line', 'The leg\'s midpoint, dashed grey.'),
        ('Target', 'Target line', 'The liquidity the setup aims for, green.'),
        ('watch', 'Watch-zone box', 'Dashed amber box: the zone the watcher is waiting on.'),
    ]),
    ('pat', 'Candlestick pattern codes', [
        ('BE', 'Bullish engulfing', 'A down candle, then an up candle whose body covers it.'),
        ('H', 'Hammer / pin bar', 'Long lower wick, little above the body: sellers pushed down, buyers took it back.'),
        ('IB', 'Inside-bar breakout', 'A candle inside the one before it, then an up close above its high.'),
        ('MS', 'Morning star', 'Strong down candle, small pause, then an up candle closing above the first one\'s middle.'),
        ('BrE', 'Bearish engulfing', 'An up candle, then a down candle whose body covers it.'),
        ('SS', 'Shooting star', 'Long upper wick, little below the body: buyers pushed up, sellers took it back.'),
        ('IBd', 'Inside-bar breakdown', 'A candle inside the one before it, then a down close below its low.'),
        ('ES', 'Evening star', 'Strong up candle, small pause, then a down candle closing below the first one\'s middle.'),
        ('▲ / ▼ marker', 'Where a pattern completed', '▲ under the candle for bullish patterns, ▼ above it for bearish ones.'),
        ('●  / amber', 'Inside the zone', 'The pattern formed inside the stock\'s zone: the ones that matter.'),
    ]),
    ('status', 'Statuses and checklist marks', [
        ('watching', 'Zone set', 'Waiting for price to reach the zone.'),
        ('tapped', 'Price in the zone', 'Waiting for a sweep and a CHoCH.'),
        ('triggered / open trade', 'Entry signalled', 'A CHoCH passed the R:R rule: an entry alert went out, and its paper trade is running.'),
        ('rejected', 'Signal skipped', 'A CHoCH came, but R:R was too low (or, intraday, after 14:30).'),
        ('expired', 'No longer watched', 'The scan stopped passing it, it was too old, the structure failed, or the session ended.'),
        ('dismissed', 'Removed by you', 'You stopped watching it.'),
        ('target / won', 'Hit the target', 'A paper trade (swing or intraday) that reached its target.'),
        ('stop / lost', 'Hit the stop', 'A paper trade that reached its stop: −1R, or worse when price gapped through it overnight.'),
        ('squared off / closed', 'Closed at 15:20', 'An intraday trade still open at square-off, closed at that price.'),
        ('≈', 'Approximate result', 'Part of a swing paper trade was judged on daily candles: the app was off for longer than 15m candles go back.'),
        ('tick · cross · … · –', 'Checklist marks', 'A tick: passed. A cross: failed. …: waiting. –: not applicable.'),
        ('−N here', 'Funnel drop', 'How many stocks stopped at that funnel step. Click the card to see which.'),
        ('forming', 'Live candle', 'The current candle, not closed yet: shown faded and never used for signals.'),
    ]),
    ('opt', 'Options mode', [
        ('OI', 'Open interest', 'Contracts open at a strike, shown in shares (contracts × lot). Writers hold most of it, so big OI is where writers expect price not to go.'),
        ('ΔOI', 'Change in OI', 'OI added (+) or closed (−) since yesterday\'s close, or since the session\'s first read where marked.'),
        ('CE / PE', 'Call / put', 'Call option (European, "CE") and put option ("PE").'),
        ('ATM', 'At the money', 'The strike nearest the underlying\'s price. Ideas buy this strike.'),
        ('ITM / OTM', 'In / out of the money', 'A call below spot (a put above it) is in the money; the other side is out of the money.'),
        ('PCR', 'Put-call ratio', 'Total put OI ÷ total call OI in the chain. Rising PCR in the session means puts are being written: usually read as bullish.'),
        ('Max pain', 'Least-payout strike', 'The expiry price at which option buyers together would collect the least. Price often drifts toward it near expiry.'),
        ('Support / resistance (OI)', 'OI walls', 'The strike with the most put OI below spot (support) and the most call OI above it (resistance).'),
        ('Long buildup', 'Price ↑ OI ↑', 'Buyers opening positions. On a call: bullish; on a put: bearish.'),
        ('Short buildup', 'Price ↓ OI ↑', 'Writers opening positions. On a call: bearish (a cap); on a put: bullish (a floor).'),
        ('Short covering', 'Price ↑ OI ↓', 'Writers closing at a loss. On a call: bullish; on a put: bearish.'),
        ('Long unwinding', 'Price ↓ OI ↓', 'Buyers closing. On a call: bearish; on a put: bullish.'),
        ('OI bias', 'Writing balance', 'From −1 to +1: put OI added minus call OI added, over the 5 strikes either side of the money. + is bullish, − bearish.'),
        ('IV', 'Implied volatility', 'The yearly volatility an option\'s price implies. High IV makes options dear to buy.'),
        ('IV pct', 'IV percentile', 'Share of past sessions whose ATM IV was below today\'s. Shown after 20 sessions of history.'),
        ('Skew', '25-delta skew', 'Put IV minus call IV at about 25 delta. Positive is normal (insurance costs more); a jump means fear.'),
        ('DTE', 'Days to expiry', 'Calendar days until the expiry; "expires today" on expiry day.'),
        ('Lot', 'Lot size', 'Shares per contract (Nifty 65, Bank Nifty 30, …). ₹ / lot in the journal is the result for one lot.'),
    ]),
    ('learn', 'Performance and the autopilot', [
        ('Total R', 'Sum of results', 'All closed trades\' results added up, in R. +12R made twelve times the usual risk.'),
        ('Avg R', 'Expectancy', 'Total R ÷ trades: what an average trade made. Above zero means the rules make money before costs.'),
        ('PF', 'Profit factor', 'R won by winners ÷ R lost by losers. Above 1 is profitable; 1.5+ is comfortable.'),
        ('Max drawdown', 'Deepest dip', 'The largest fall of the cumulative R from a previous high: the worst run you would have sat through.'),
        ('Backtest', 'Replay of history', 'Years of candles run through the same rule code as the live alerts, in the lab container.'),
        ('Out of sample', 'Unseen data', 'Results on a period the tuning never looked at: the only honest test of tuned rules.'),
        ('Walk-forward', 'Tune, then test ahead', 'Tune on the past, judge on the next 3 months, roll forward; repeated across the history.'),
        ('Shadow', 'Trial run', 'Proposed rules replayed on new data next to the live rules before anything changes.'),
        ('Rollback', 'Change undone', 'The autopilot puts the previous rules back when live results after a change go badly.'),
        ('Paused', 'Alerts muted', 'A mode\'s Telegram entry alerts stop after a losing streak; trades are still recorded.'),
        ('Candidate', 'Near-idea', 'An options read that came close to an idea, kept so the autopilot can test looser or tighter rules.'),
    ]),
    ('market', 'Market, data and units', [
        ('NSE', 'National Stock Exchange of India', 'Where every stock here trades.'),
        ('IST', 'India Standard Time', 'UTC+5:30. Every time in the app is IST.'),
        ('Nifty 50 / 100 / 200 / 500', 'NSE indices', 'The largest 50, 100, 200 or 500 NSE companies, from niftyindices.com.'),
        ('PSU', 'Public sector undertaking', 'A government-owned company (as in Nifty PSU Bank).'),
        ('CPSE / PSE', 'Central public sector enterprise / public sector enterprise', 'Government-owned company indices.'),
        ('FMCG', 'Fast-moving consumer goods', 'A sector index.'),
        ('IT', 'Information technology', 'A sector index.'),
        ('MNC', 'Multinational company', 'Indian-listed subsidiaries of foreign groups.'),
        ('D / 5m / 15m / 1m', 'Timeframes', 'Daily, 5-minute, 15-minute and 1-minute candles.'),
        ('3M / 6M / 1Y', 'Chart range', 'The last 3 months, 6 months or 1 year of daily candles.'),
        ('L', 'Lakh', '100,000. 10 L = 1,000,000 shares.'),
        ('Cr', 'Crore', '10,000,000 (100 lakh).'),
        ('K', 'Thousand', '1,000.'),
        ('Dhan', 'Broker data feed', 'Real-time quotes and candles from Dhan\'s Data API, when connected.'),
        ('yfinance', 'Yahoo Finance data', 'Free data, delayed a few minutes. Used when Dhan isn\'t connected.'),
        ('TOTP', 'Time-based one-time password', 'The 6-digit authenticator code used for Dhan\'s automatic daily login.'),
    ]),
]


def as_json() -> List[Dict]:
    return [{'key': k, 'title': t, 'terms': [{'term': a, 'name': b, 'meaning': c} for a, b, c in items]}
            for k, t, items in GROUPS]


def markdown() -> str:
    """The README's glossary section body (between its markers)."""
    out = []
    for _, title, items in GROUPS:
        out.append(f'### {title}\n\n| Term | Stands for | Meaning |\n|---|---|---|')
        out += [f'| **{a.replace("|", "/")}** | {b} | {c} |' for a, b, c in items]
        out.append('')
    return '\n'.join(out).rstrip() + '\n'
